language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

install:
  - composer require satooshi/php-coveralls:~1.0@stable

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'